core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views 
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path("",views.home, name="home"),
    path('signup/',views.signup, name='signup'),
    path('logout/',auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('login/', auth_views.LoginView.as_view(next_page='/',template_name='core/login.html', authentication_form=LoginForm), name='login')
]

janken/urls.py
from django.urls import path
from . import views 

app_name = 'janken'

urlpatterns = [
    path("",views.Play.as_view(), name="play"),
    path("/choice",views.game_choice,name="choice"),
]

janken_video/urls.py
from django.urls import path
from . import views 

app_name = 'janken_video'

urlpatterns = [
    path("/livestream",views.another,name="video_test"),
    path("/frame-streaming", views.frame_streaming, name="frame-streaming")
]

shifumi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("core.urls")),
    path("play", include("janken.urls")),
    path("play", include("janken_video.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

core/models.py
from django.db import models

# Create your models here.

janken/models.py
from django.db import models

# Create your models here.

janken_video/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'password',
        'class':'w-full py-4 px-6 rounded-xl'
    }))
        

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email','password1','password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username',
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'password',
        'class':'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': ' repeat password',
        'class':'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_protect

@require_http_methods(["GET"])
def home(request):
    return render(request,
                  "core/home.html")

@csrf_protect
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html',{
        'form':form 
    })
@csrf_protect
@login_required
def logout_view(request):
    logout(request)
    return redirect('/')

janken/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views import View
import random
# Create your views here.


def game_choice(request):
    return render(request,"janken/game_choice.html")

class Play(View) :
    def get(self, request):
        resultat = "start"
        return render(request,"janken/play.html",{"resultat":resultat})

    def post(self, request) :
        nombre_coups_possibles = 3
        coup_pc = random.randint(1,nombre_coups_possibles)
        coup_user = int(request.POST["pierre"])

        print(coup_user)
        coup_user_modulo = coup_user % nombre_coups_possibles
        coup_pc_modulo = coup_pc % nombre_coups_possibles

        if coup_pc == coup_user :
            resultat = "Egalité ! Rompez "
            id = 0 
        elif coup_user_modulo == coup_pc_modulo + 1: 
            resultat = " Défaite implacable !"
            id = -1
        else :
            resultat = " Victoire Ecrasante ! "
            id = 1 
        
        return render(request,"janken/play.html",{"resultat":resultat, "id":id})

janken_video/views.py
from django.shortcuts import render
from django.views.decorators import gzip
from django.http import StreamingHttpResponse, HttpResponse
from django.views.decorators.http import require_http_methods
import cv2
from django.views.decorators.csrf import csrf_exempt
import threading
import json
from PIL import Image
import base64
import io
import numpy as np
from .preprocess import * 
from .predict import *
from .rpc import jouer
import os

def another(request):
    print(os.getcwd())
    return render(request,"janken_video/camera2.html")


@csrf_exempt # !!! NEVER DO THIS EXCEPT IF YOU KNOW, WAS DONE JUST CAUSE I WAS LAZY  
def frame_streaming(request):

    # ugly way to deal with an image
    try:
        
        data_received = json.loads(request.body)
        print('Data received:', data_received.keys())
    except json.JSONDecodeError as e:
        print('Error decoding JSON:', e)

    # get the image value
    image_b64  = data_received['image']

    # add the == to decode the image
    base64_decoded = base64.b64decode(image_b64+ "==")

    # 
    image = Image.open(io.BytesIO(base64_decoded))
    image_np = np.array(image)

    image_rgb = image_np[:,:,:3]

    print("Dimension de l'image enregistrée : ", image_rgb.shape)

    #----PREPROCESS + PREDICTION --------------------------------------------------------------------------------------------

    image_preprocessed = preprocess_image(image_rgb)

    label_predicted = predict_coup(image_preprocessed)

    #-------------------------------------------------------------------------------------------------

    resultat_partie = jouer(label_predicted)

    resultat = json.dumps(resultat_partie)

    # Create an HttpResponse object and returning it 
    response = HttpResponse(content=resultat, content_type='application/json')
    response['Access-Control-Allow-Origin'] = 'http://127.0.0.1:8000/liveplay/livestream'
    response['Access-Control-Allow-Methods'] = 'GET, POST, OPTIONS'
    response['Access-Control-Allow-Headers'] = 'Content-Type'

    return response

core/templates/core/base.html
{% load static %}
{% load static tailwind_tags %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- <script src="https://cdn.tailwindcss.com"></script> -->
        {% tailwind_css %}
        <link rel="icon" type="image/x-icon" href="{% static 'core/images/shuriken.png' %}">
        <link  href="{% static 'core/styles.css' %}" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
        <title>{% block title %}{% endblock %} | Shifumi </title>

    </head>
    <body class="bg-black">
        <nav class="py-8 px-6 flex  items-center border-b border-grey-200 bg-black">
            <div class="flex  w-2/3 ">
                <!-- <a href="/" class="text-3xl font-semibold">
                    <img src="{% static 'core/images/shuriken.png' %}" alt="Logo" class="object-scale-down w-28 rounded-xl">
                </a> -->
                    <a href="/" class="font-permanent-marker absolute left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-6xl font-semibold mt-2 ml-6 text-white"> Shifumi </a>
            </div>
            <div class="space-x-2 w-1/3 flex justify-end">
                <a href="#" class="text-center w-1/4 py-3 text-lg font-semibold hover:text-gray-500 "> Browse </a>
                <a href="#" class=" text-center w-1/4 px-2 py-3 text-lg font-semibold bg-amber-500 text-white rounded-xl hover:bg-amber-700"> Dashboard </a>
                <a href="#" class="text-center w-1/4 px-3 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-amber-700"> Settings</a>
                <a href="{% url 'core:logout' %}" class="text-center w-1/4 px-3 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-red-700"> Logout</a>
                <a href="#" class="text-center px-5 py-3 w-1/3 text-lg font-semibold hover:text-gray-500"> Ninja ! </a>
                <a href="{% url 'core:signup' %}" class="text-center px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700"> Sign up</a>
                <a href="{% url 'core:login' %}" class="text-center px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-red-700"> Log in </a>
            </div>
        </nav>
        <div class="px-6 py-6 min-h-screen flex flex-col items-center">
            {% block content %}
            {% endblock %}
        </div>
        <footer class="py-6 px-6 flex justify-between bg-gray-800 ">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400"> About </h3>

                <p class="text-lg text-gray-500">Lorem ipsum dolor sit amet consectetur adipisicing elit. A ea quibusdam nemo ipsam consectetur odio. 
                    Ratione magnam exercitationem enim. Dignissimos cumque non reprehenderit odio qui aliquid, laborum incidunt architecto tenetur.</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400"> Menu </h3>
                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-gray-500 hover:text-grey-300">About</a></li>
                    <li><a href="#" class="text-lg text-gray-500 hover:text-grey-300">Contact</a></li>
                    <li><a href="#" class="text-lg text-gray-500 hover:text-grey-300">Privacy</a></li>
                    <li><a href="#" class="text-lg text-gray-500 hover:text-grey-300">Terms of use</a></li>
                </ul>
            </div>

        </footer>
    </body>
    {% block extra_body %}
    {% endblock %}
</html>

core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}  {% endblock %}
{% block content %}
<div class="p-6 flex flex-col items-center">
    <div class="mt-10 w-5/6">
        <img src="{% static 'core/images/main_img.jpg'%}" alt="" class="rounded-xl h-5/6" title="Gon Freecs.">
    </div>
    <div class="flex justify-around w-full mt-5">
                    <a href="{% url 'janken:choice' %}" class="py-8 px-16 text-4xl bg-green-500 hover:bg-green-600 rounded-xl text-white mt-10 w-5/6 text-center font-semibold"> Jouez !  </a>
    </div>
</div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}
{% block title %} Login {% endblock %}
{% block content %}
<div class="w-1/2 p-6 mu-6 mx-auto bg-gray-100 rounded-xl mt-10">
    <div class="flex justify-center">
        <h1 class="mb-6 text-3xl"> Login </h1>
    </div>
    <form method="post" action="." >
        {% csrf_token %}
            <div class="mb-3">
                <label class="inline-block mb-2"> Username </label> <br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2 mb-2"> Password </label><br>
                {{ form.password }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {%for field in form %}
                        {{ field.errors}}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <div>
                <a href="{% url 'core:signup' %}" class="underline text-lg text-slate-400 mt-2 ">Vous n'avez pas de compte ? Enregistrez-vous </a>
            </div>
            <div>
                <a href="#" class="underline text-lg text-slate-400 mt-2 "> Mot de passe oublié ?  </a>
            </div>
            <button class="py-4 px-8 text-lg bg-amber-500 hover:bg-amber-600 rounded-xl text-white mt-5 w-1/5"> Login  </button>
    </form>
    

</div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}
{% block title %} Sign Up {% endblock %}
{% block content %}
<div class="w-1/2 p-6 mu-6 mx-auto bg-gray-100 rounded-xl mt-10">
    <div>
        <h1 class="mb-6 text-3xl"> Sign Up</h1>
    </div>
    <form method="post" action="." >
        {% csrf_token %}
            <div class="mb-3">
                <label class="inline-block mb-2"> Username </label> <br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2"> Email</label><br>
                {{ form.email }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2 mb-2"> Password </label><br>
                {{ form.password1 }}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2 mb-2"> Repeat Password </label><br>
                {{ form.password2 }}
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {%for field in form %}
                        {{ field.errors}}
                    {% endfor %}
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
        <div class="flex justify-center mt-5">
            <button class="py-4 px-8 text-lg bg-amber-500 hover:bg-amber-600 rounded-xl text-white w-full font-semibold"> Submit </button>
        </div>
    </form>

</div>
{% endblock %}

janken/templates/janken/game_choice.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}  {% endblock %}
{% block content %}
<div class="p-6 flex flex-col items-center">
    <div class=" flex flex-col items-center ">
        <img src="{% static 'janken/images/jeu1.jpg'%}" alt="" class="rounded-xl" title="Thous">
    </div>
    <h1 class="mt-10 text-white text-5xl"> Choix du Jeu : </h1>
    <div class="mt-10 flex items-center w-full">
        <div class="mt-10 w-1/2 ">
            <a href="{% url 'janken:play' %}" class="image1 mt-10 py-6 px-16 text-4xl rounded-xl text-white text-center font-semibold"> Shifumi Click'</a>
        </div>
        <div class="mt-10 ml-20 w-1/2">
            <a href="{% url 'janken_video:video_test' %}" class=" py-6 px-16 text-4xl bg-red-500 red_dark rounded-xl text-white text-center font-semibold"> Shifumi Live'</a>
        </div>
    </div>
</div>
{% endblock %}

janken/templates/janken/play.html
{%extends 'core/base.html' %}
{% load static %}
{% block title %}  {% endblock %}
{% block content %}
<div class="p-6 flex flex-col items-center">
    <div id="counter_box">
        {% if resultat == "start" %}
            <h1 id="1" class="text-white text-6xl">0</h1>
        {% endif %}
    </div>
    <form class="flex justify-around w-full mt-5" method="post">
        {% csrf_token %}
        <div class="w-3/12">
            <!-- <input type="image" name="coup" value="1" alt="pierre" class="rounded-xl w-full " src="{% static 'janken/images/pierre.jpg'%}"> -->
            <button name="pierre" value="1" onclick="reset_timer()"><img src="{% static 'janken/images/pierre.jpg'%}" alt="" class="rounded-xl w-full "></button>
            <h2 class="text-white text-center text-5xl mt-2"> Pierre </h2>
        </div>
        <div class="w-3/12">
            <!-- <input type="image" name="coup2" value="2" alt="feuille" class="rounded-xl w-full " src="{% static 'janken/images/feuille.jpg'%}"> -->
            <button name="pierre" value="2" onclick="reset_timer()"> <img src="{% static 'janken/images/feuille.jpg'%}" alt="" class="rounded-xl w-full"></button>
            <h2 class="text-white text-center text-5xl mt-2"> Feuille </h2>
        </div>
        <div class="w-3/12">
            <!-- <input type="image" name="coup3" value="3" alt="ciseaux" class="rounded-xl w-full " src="{% static 'janken/images/ciseaux.jpg'%}"> -->
            <button name="pierre" value="3" onclick="reset_timer()"><img src="{% static 'janken/images/ciseaux.jpg'%}" alt="" class="rounded-xl w-full "></button>
            <h2 class="text-white text-center text-5xl mt-2"> Ciseaux </h2>
        </div>
    </form>
</div>
{% if resultat != "start" %}
    {% if id == 0 %}
        <div class="text-5xl mt-5 text-orange-400" id="result">{{resultat}}</div>
    {% elif id == -1 %}
        <div class="text-5xl mt-5 text-red-500" id="result">{{resultat}}</div>
    {% elif id == 1 %}
        <div class="text-5xl mt-5 text-green-500" id="result">{{resultat}}</div>
    {% endif %}
    <a href="#" id="try_again" onclick="reset_timer()" class="py-8 px-16 text-4xl bg-purple-500 hover:bg-purple-600 rounded-xl text-white mt-10 w-5/6 text-center font-semibold" id="2"> Nouvelle partie ? </a>
{% endif %}

<script>
    let interval;
    var i = 10 ;
    document.getElementById("1").innerHTML = i 
    function reset_timer(){
        var counter_box = document.getElementById("counter_box") ;
        var try_again = document.getElementById("try_again") ;
        var result_elem = document.getElementById("resultat");
        if (counter_box.innerHTML != "TIC TAC BOUM"){
            counter_box.innerHTML = '<h1 id="1" class="text-white text-6xl">0</h1>';
        }
        if(result_elem != null){
            result_elem.remove();
            try_again.remove() ; 
        }

        if (interval){
            clearInterval(interval);
            interval = null;
            i = 10;
        }else{
            timer();
        }
    }
    function change_number(){
        document.getElementById("1").innerHTML = i ; 
        i-=1;
        console.log(document.getElementById("1").innerHTML);
        if(i == 0){
            document.getElementById("1").innerHTML = "TIC TAC BOUM" ; 
            alert("TIC TAC BOUM")
            reset_timer()
        }
    }
    function timer(){
        if(!interval){
            change_number();
            interval  = setInterval(change_number, 1000);
        }
    }
    reset_timer();
</script>
{% endblock %}

janken_video/templates/janken_video/camera2.html
{%extends 'core/base.html' %}
{% load static %}
{% block title %} Camera {% endblock %}
{% block content %}
  <div id="counter_box">
        <h1 id="1" class="text-white text-6xl">5</h1>
  </div>
  <div class="text-5xl mt-5 text-orange-400" id="result"></div>
    <div class="flex flex-col items-center">
        <video id="video" class="rounded-xl mt-10" >Video stream not available.</video>
        <button id="startbutton" class="mt-10 rounded-xl text-3xl py-8 px-8 bg-purple-500 hover:bg-purple-600"> JOUER ! 遊ぶ </button>
    </div>
    <canvas id="canvas" hidden> </canvas>
 
<script>
  // IMPORTANT  : 
  // code from mmozilla dev : https://developer.mozilla.org/en-US/docs/Web/API/Media_Capture_and_Streams_API/Taking_still_photos

  (() => {
  // The width and height of the captured photo. We will set the
  // width to the value defined here, but the height will be
  // calculated based on the aspect ratio of the input stream.

  const width = 500; // We will scale the photo width to this
  let height = 0; // This will be computed based on the input stream

  // |streaming| indicates whether or not we're currently streaming
  // video from the camera. Obviously, we start at false.

  let streaming = false;

  // The various HTML elements we need to configure or control. These
  // will be set by the startup() function.

  let video = null;
  let canvas = null;
  let photo = null;
  let startbutton = null;

  function showViewLiveResultButton() {
    if (window.self !== window.top) {
      // Ensure that if our document is in a frame, we get the user
      // to first open it in its own tab or window. Otherwise, it
      // won't be able to request permission for camera access.
      document.querySelector(".contentarea").remove();
      const button = document.createElement("button");
      button.textContent = "View live result of the example code above";
      document.body.append(button);
      button.addEventListener("click", () => window.open(location.href));
      return true;
    }
    return false;
  }

  function startup() {
    if (showViewLiveResultButton()) {
      return;
    }
    video = document.getElementById("video");
    canvas = document.getElementById("canvas");
    startbutton = document.getElementById("startbutton");

    navigator.mediaDevices
      .getUserMedia({ video: true, audio: false })
      .then((stream) => {
        video.srcObject = stream;
        video.play();
      })
      .catch((err) => {
        console.error(`An error occurred: ${err}`);
      });

    video.addEventListener(
      "canplay",
      (ev) => {
        if (!streaming) {
          height = video.videoHeight / (video.videoWidth / width);

          // Firefox currently has a bug where the height can't be read from
          // the video, so we will make assumptions if this happens.

          if (isNaN(height)) {
            height = width / (4 / 3);
          }

          video.setAttribute("width", width);
          video.setAttribute("height", height);
          canvas.setAttribute("width", width);
          canvas.setAttribute("height", height);
          streaming = true;
        }
      },
      false,
    );

    startbutton.addEventListener(
      "click",
      (ev) => {
        // takepicture();
        reset_timer();
        ev.preventDefault();
      },
      false,
    );

    clearphoto();
  }

  // Fill the photo with an indication that none has been
  // captured.

  function clearphoto() {
    const context = canvas.getContext("2d");
    context.fillStyle = "#AAA";
    context.fillRect(0, 0, canvas.width, canvas.height);

    const data = canvas.toDataURL("image/png");
    // photo.setAttribute("src", data);
  }

  // Capture a photo by fetching the current contents of the video
  // and drawing it into a canvas, then converting that to a PNG
  // format data URL. By drawing it on an offscreen canvas and then
  // drawing that to the screen, we can change its size and/or apply
  // other changes before drawing it.

  function takepicture() {
    const context = canvas.getContext("2d");
    if (width && height) {
      canvas.width = width;
      canvas.height = height;
      context.drawImage(video, 0, 0, width, height);

      const data = canvas.toDataURL("image/png");

      
  

      // ---- SENDING DATA IMAGE --------------------------------------------------------- //

    // removing the text that is not the b64 image
    const data_to_send = data.slice(22);

    // Create a JSON object with the base64-encoded image data
    const dataToSend = {
    image: data_to_send,
    };

    const serverUrl = 'http://localhost:8000/play/frame-streaming';

    // Make a POST request using the fetch API
    fetch(serverUrl, {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json',
    },
    body: JSON.stringify(dataToSend),
    
    })
    .then(response => {
        if (!response.ok) {
        throw new Error('Network response was not ok');
        }
        console.log(response.json().then(function(result){
          console.log(result)
          alert(result["resultat"])
          document.getElementById("result").innerHTML = "Vous avez jouez :" + result["coup_user"]
        }))
        return response
    })
    .then(data => {
        // Handle the server's response
        console.log('Server response:', data);
    })
    .catch(error => {
        // Handle errors during the fetch
        console.error('Error during fetch:', error);
    });
    // --- END OF TEST -----------------------------------------------------------
    } else {
      clearphoto();
    }
  }

  // Set up our event listener to run the startup process
  // once loading is complete.
  window.addEventListener("load", startup, false);

  //##TIMER##############################################################################################
  let interval;
    var i = 5 ;
    document.getElementById("1").innerHTML = i 
    function reset_timer(){
        var counter_box = document.getElementById("counter_box") ;
        if (counter_box.innerHTML != "TIC TAC BOUM"){
            counter_box.innerHTML = '<h1 id="1" class="text-white text-6xl">0</h1>';
        }
        if (interval){
            clearInterval(interval);
            interval = null;
            i = 5;
        }else{
            timer();
        }
    }
    function change_number(){
        document.getElementById("1").innerHTML = i-1 ; 
        i-=1;
        console.log(document.getElementById("1").innerHTML);
        if(i == 0){
            document.getElementById("1").innerHTML = "TIC TAC BOUM" ; 
            takepicture();
            alert("Wait for a minute while the image is processed")
            reset_timer();
        }
    }
    function timer(){
        if(!interval){
            change_number();
            interval  = setInterval(change_number, 1000);
        }
    }
})();

</script>
{% endblock %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>